site_name: Stream Viewer
repo_url: https://github.com/intheon/StreamViewer/
theme:
  name: "material"
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search
  - mkdocstrings
nav:
  - Home: README.md
  - Modules:
    - Renderers:
      - Overview: modules/renderers/overview.md
      - Architecture: modules/renderers/architecture.md
      - Development Guide: modules/renderers/development-guide.md
      - Annotated Examples: modules/renderers/annotated-examples.md
