[general]
debug = 1
; this maps input to sounds

[link 1]
source = input.0  ; First channel of your dataframe
destination = output.pitch

[link 2]
source = input.1 ; Second channel of your dataframe
destination = output.velocity